// Karma configuration
// Generated on Wed Apr 23 2014 12:35:04 GMT+0530 (IST)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/libs/angular.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/libs/angular-cookies.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/libs/angular-route.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/libs/angular-mocks.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/libs/ui-bootstrap-tpls-0.10.0.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/utils/Base64.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/libs/ng-table.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/AdminUtilityApp.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/controllers/ManageProviderController.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/tests/ManageProviderControllerTest.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/controllers/AdminLoginController.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/tests/AdminLoginControllerTest.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/controllers/ManageClientController.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/tests/ManageClientControllerTest.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/controllers/CreateProviderController.js',
      '/home/cts1/workspaces/Utility/APIGatewayWebApp/WebContent/scripts/tests/CreateProviderControllerTest.js'
    ],


    // list of files to exclude
    exclude: [
      
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  });
};
